name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: gigi
          MYSQL_DATABASE: app_test
          MYSQL_USER: gigi
          MYSQL_PASSWORD: gigi
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_mysql
        coverage: none
    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist
      working-directory: ./project
    - name: Copy .env.testing
      run: cp .env.testing .env
      working-directory: ./project
    - name: Generate application key
      run: php artisan key:generate
      working-directory: ./project
    - name: Wait for MySQL
      run: while ! mysqladmin ping -h127.0.0.1 -P3306 -ugigi -pgigi --silent; do sleep 1; done
      working-directory: ./project
    - name: Run Laravel tests
      run: php artisan test
      working-directory: ./project

  angular-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install Angular dependencies
      run: npm ci
      working-directory: ./project/resources/crud-angular
    - name: Run Angular tests
      run: npm test -- --watch=false --browsers=ChromeHeadless
      working-directory: ./project/resources/crud-angular